########################################
# Docker build
########################################
#time sudo docker build -t naisy/jetson-jp461-espnet2-tts -f Dockerfile.jetson-jp461-espnet2-tts .


########################################
# Storage setting
########################################
#sudo service docker stop
#cd /var/run
#sudo mv docker /mnt/ssd250
#sudo ln -s /mnt/ssd250 docker
#sudo service docker start

# https://github.com/NVIDIA/nvidia-docker/issues/1033
# cmake fails unable to find cuda library while building an image
#vi /etc/docker/daemon.json
#{
#    "runtimes": {
#        "nvidia": {
#            "path": "/usr/bin/nvidia-container-runtime",
#            "runtimeArgs": []
#        }
#    },
#    "default-runtime": "nvidia"
#}
#
#service docker stop
#service docker start


# end of information


########################################
# Base OS repogitory
########################################
# DeepStream-l4t tags: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/deepstream-l4t/tags

ARG BASE_IMAGE=naisy/jetson-jp461-deepstream601-triton-base
FROM ${BASE_IMAGE}

ARG USERNAME=jetson
ARG OPENBLAS_CORETYPE=ARMV8
ARG VENV=python3

USER $USERNAME

########################################
# espnet2_tts
########################################
RUN . /virtualenv/$VENV/bin/activate \
    && sudo apt-get update \
    && sudo apt-get install -y \
      llvm-10-dev \
    && cd ~/github \
    && git clone https://github.com/espnet/espnet \
    && cd espnet \
    && sed -i 's|python_requires=">=3.7.0",|python_requires=">=3.6.9",|g' setup.py \
    && sed -i 's|"Programming Language :: Python :: 3",|"Programming Language :: Python :: 3",\n        "Programming Language :: Python :: 3.6",|g' setup.py \
    && LLVM_CONFIG=/usr/lib/llvm-10/bin/llvm-config pip install -e . \
    && cd espnet2/gan_tts/vits/monotonic_align \
    && pip install -e . \
    && cd ~/github \
    && git clone https://github.com/espnet/espnet_model_zoo \
    && cd espnet_model_zoo \
    && pip install -e . \
    && sudo apt autoremove -y \
    && sudo rm -rf /var/lib/apt/lists/*

RUN sudo sed -i 's/docker-/docker-espnet2-tts-/g' /root/.bashrc \
    && sed -i 's/docker-/docker-espnet2-tts-/g' /home/$USERNAME/.bashrc


CMD . /virtualenv/python3/bin/activate && exec bash -c "jupyter-lab --ip=0.0.0.0 --no-browser --ServerApp.root_dir=/ --LabApp.default_url=/lab?file-browser-path=$HOME/data/Notebooks"
