########################################
# Docker build
########################################
#time sudo docker build -t naisy/jetson-jp461-jetracer-ai86 -f Dockerfile_jetson-jp461-jetracer-ai86 .


########################################
# Storage setting
########################################
#sudo service docker stop
#cd /var/lib
#sudo mv docker /mnt/ssd250
#sudo ln -s /mnt/ssd250 docker
#sudo service docker start

# https://github.com/NVIDIA/nvidia-docker/issues/1033
# cmake fails unable to find cuda library while building an image
#vi /etc/docker/daemon.json
#{
#    "runtimes": {
#        "nvidia": {
#            "path": "/usr/bin/nvidia-container-runtime",
#            "runtimeArgs": []
#        }
#    },
#    "default-runtime": "nvidia"
#}
#
#service docker stop
#service docker start


# end of information


########################################
# Base OS repogitory
########################################
ARG BASE_IMAGE=naisy/jetson-jp461-deepstream601-triton-base
FROM ${BASE_IMAGE}

ARG USERNAME=jetson
ARG OPENBLAS_CORETYPE=ARMV8
ARG VENV=python3


########################################
# JetRacer AI86
########################################
RUN . /virtualenv/$VENV/bin/activate \
    ### FaBo PCA9685
    && cd ~/github \
    && git clone -b jupyterlab https://github.com/FaBoPlatform/FaBoPWM-PCA9685-Python \
    && cd FaBoPWM-PCA9685-Python \
    && pip install . \
    ### JetRacer
    && cd ~/github \
    && git clone https://github.com/FaBoPlatform/jetracer \
    && cd jetracer \
    && pip install -e . \
    && cp -r notebooks ~/notebooks \
    ### JetCam
    && cd ~/github \
    && git clone https://github.com/NVIDIA-AI-IOT/jetcam \
    && cd jetcam \
    && pip install -e . \
    ### OLED IP Address
    && cd ~/github \
    && git clone https://github.com/FaBoPlatform/ip_address_display \
    && cd ip_address_display \
    && mkdir -p ~/bin \
    && cp oled_ip_jetson.py ~/bin \
    && cp oled_ip.sh ~/bin \
    && sed -i '/oled/d' ~/bin/oled_ip.sh \
    && echo '/virtualenv/python3/bin/python /home/$(getent passwd 1000 | cut -d: -f1)/bin/oled_ip_jetson.py' >> ~/bin/oled_ip.sh


RUN sudo sed -i 's/docker-/docker-jetracer-ai86-/g' /root/.bashrc \
    && sed -i 's/docker-/docker-jetracer-ai86-/g' /home/$USERNAME/.bashrc


CMD . /virtualenv/python3/bin/activate && exec bash -c "jupyter-lab --ip=0.0.0.0 --no-browser --ServerApp.root_dir=/ --LabApp.default_url=/lab?file-browser-path=$HOME/data/Notebooks"

