########################################
# Docker build
########################################
#time sudo docker build -t naisy/jetson-jp461-donkeycar-overdrive4 -f Dockerfile_jetson-jp461-donkeycar-overdrive4 .


########################################
# Storage setting
########################################
#sudo service docker stop
#cd /var/lib
#sudo mv docker /mnt/ssd250
#sudo ln -s /mnt/ssd250 docker
#sudo service docker start

# https://github.com/NVIDIA/nvidia-docker/issues/1033
# cmake fails unable to find cuda library while building an image
#vi /etc/docker/daemon.json
#{
#    "runtimes": {
#        "nvidia": {
#            "path": "/usr/bin/nvidia-container-runtime",
#            "runtimeArgs": []
#        }
#    },
#    "default-runtime": "nvidia"
#}
#
#service docker stop
#service docker start


# end of information


########################################
# Base OS repogitory
########################################
ARG BASE_IMAGE=naisy/jetson-jp461-deepstream601-triton-base
FROM ${BASE_IMAGE}

ARG USERNAME=jetson
ARG OPENBLAS_CORETYPE=ARMV8
ARG VENV=python3


########################################
# JupyterLab terminal DEFAULT_ANSI_COLORS Tango to Rxvt-LightBlue/Aquamarine
########################################
RUN grep -rl --include=\*.js --include=\*.ts --include=\*.css --include=\*.html \
    "#3465a4" /virtualenv/python3/share/jupyter \
  | while read file; do \
    echo "パッチ中: $file"; \
    sed -i '\
      s/#2e3436/#000000/g;\
      s/#cc0000/#cd0000/g;\
      s/#4e9a06/#00cd00/g;\
      s/#c4a000/#cdcd00/g;\
      s/#3465a4/#add8e6/g;\
      s/#75507b/#cd00cd/g;\
      s/#06989a/#00cdcd/g;\
      s/#d3d7cf/#faebd7/g;\
      s/#555753/#404040/g;\
      s/#ef2929/#ff0000/g;\
      s/#8ae234/#00ff00/g;\
      s/#fce94f/#ffff00/g;\
      s/#729fcf/#7fffd4/g;\
      s/#ad7fa8/#ff00ff/g;\
      s/#34e2e2/#00ffff/g;\
      s/#eeeeec/#ffffff/g;\
    ' "$file"; \
  done

# jupyterlab mouse click event
RUN . /virtualenv/$VENV/bin/activate \
    && pip install --no-deps \
      ipyevents==2.0.2 \
      orjson==3.6.1


# DSR Alpha Zero
RUN . /virtualenv/$VENV/bin/activate \
    && pip install --no-deps \
      lmdb==1.6.2 \
      lz4

########################################
# DonkeyCar OVERDRIVE4
########################################
RUN . /virtualenv/$VENV/bin/activate \
    && cd ~/github \
    && git clone -b overdrive4 https://github.com/naisy/donkeycar \
    && git clone https://github.com/naisy/overdrive \
    && git clone https://github.com/naisy/donkeycar_tools \
    && cd donkeycar \
    && pip install -e .[nano]


RUN . /virtualenv/$VENV/bin/activate \
    && cd ~/github \
    && git clone https://github.com/tawnkramer/gym-donkeycar \
    && cd gym-donkeycar \
    && sed -i 's/python_requires=">=3\.7"/python_requires=">=3.6"/g' setup.py \
    && sed -i 's|^requirements = \["gym==0.22", "numpy", "pillow"\]|requirements = []|g' setup.py \
    && pip install -e .


RUN sudo sed -i 's/docker-/docker-donkeycar-overdrive4-/g' /root/.bashrc \
    && sed -i 's/docker-/docker-donkeycar-overdrive4-/g' /home/$USERNAME/.bashrc


CMD . /virtualenv/python3/bin/activate && exec bash -c "jupyter-lab --ip=0.0.0.0 --no-browser --ServerApp.root_dir=/ --LabApp.default_url=/lab?file-browser-path=$HOME/data/Notebooks"

